### ISSUE TITLE
Unable to download data

### ISSUE THREAD

**Issue by MiguelMonteiro** [neurodata/ndpull#4]
When using command line API or the python program examples I am unable to download any data. Both these methods result in the following error message:
```
Traceback (most recent call last):
  File "/usr/local/bin/ndpull", line 11, in <module>
    load_entry_point('ndpull==1.0.1', 'console_scripts', 'ndpull')()
  File "/usr/local/lib/python3.6/site-packages/ndpull/ndpull.py", line 337, in main
    result, rmt = validate_args(args)
  File "/usr/local/lib/python3.6/site-packages/ndpull/ndpull.py", line 312, in validate_args
    full_range = rmt.get_xyz_extents()
  File "/usr/local/lib/python3.6/site-packages/ndpull/ndpull.py", line 116, in get_xyz_extents
    coord_frame = self.get_coord_frame_metadata()
  File "/usr/local/lib/python3.6/site-packages/ndpull/ndpull.py", line 105, in get_coord_frame_metadata
    coord_frame_name = self.get_coord_frame_name(exp_metadata)
  File "/usr/local/lib/python3.6/site-packages/ndpull/ndpull.py", line 113, in get_coord_frame_name
    return exp_data['coord_frame']
KeyError: 'coord_frame'
```

Seems like some part of the code tries to access a dictionary member that does not yet exist at that point in the program. 

Any ideas on how to fix this issue?

Thanks in advance!

**Comment by falkben** [comment]
It's is working for me (our services are online).  

Can you report the commands you used?  Also, you did create an account at https://api.boss.neurodata.io/ and used the token found here: https://api.boss.neurodata.io/v1/mgmt/token

**Comment by MiguelMonteiro** [comment]
I had accidentally appended an extra character to the token, sorry. It is working now, thanks.
